import { Graph } from "./api";

export const defGraph = (): Graph => ({
    types: [
        {
            id: "precise",
            userEnabled: false,
            type: "1",
            enabledBy: [["choice"]],
            disabledBy: [["imprecise"]],
            properties: [
                "control_over_each_place_value",
                "control_over_degree_of_precision",
                "number_is_thing_of_interest",
            ],
        },
        {
            id: "imprecise",
            userEnabled: false,
            type: "1",
            enabledBy: [],
            disabledBy: [["precise"], ["choice"]],
            properties: [
                "number_not_real_thing_of_interest",
                "sketch_of_a number",
                "may_evolve_into_needing_precise_value",
            ],
        },
        {
            id: "unexpected",
            userEnabled: false,
            type: "1",
            enabledBy: [],
            disabledBy: [["counting"], ["known"]],
            properties: [
                "often_random",
                "mapped_to_something_unusual",
                "form_of_exploration",
                "looking_for_surprise",
                "breaking_from_self",
            ],
        },
        {
            id: "counting",
            userEnabled: false,
            type: "1",
            enabledBy: [],
            disabledBy: [["unexpected"]],
            properties: [
                "keeping_track_of_something",
                "primarily_increasing_not_decreasing",
                "increment_control",
                "decrement_control",
                "reset_control",
            ],
        },
        {
            id: "choice",
            userEnabled: false,
            type: "1",
            enabledBy: [],
            disabledBy: [["unbounded"], ["known"], ["counting"]],
            properties: ["limited_selection"],
        },
        {
            id: "adjustment",
            userEnabled: false,
            type: "2",
            enabledBy: [],
            disabledBy: [["set_once"]],
            properties: [
                "decreased_range",
                "increased_precision",
                "avoid_modal_changes",
                "fluent_mental_model",
            ],
        },
        {
            id: "set_once",
            userEnabled: false,
            type: "2",
            enabledBy: [],
            disabledBy: [["adjustment"]],
            properties: ["speed_or_number_of_steps_low_priority"],
        },
        {
            id: "known",
            userEnabled: false,
            type: "2",
            enabledBy: [],
            disabledBy: [["unknown"]],
            properties: ["minimise_error", "adjustment_low_priority"],
        },
        {
            id: "unknown",
            userEnabled: false,
            type: "2",
            enabledBy: [],
            disabledBy: [["known"]],
            properties: [
                "adjustment_important",
                "prioritise_speed",
                "ease_of_comparison_important",
            ],
        },
        {
            id: "bounded",
            userEnabled: false,
            type: "2",
            enabledBy: [["choice"], ["known", "unexpected"]],
            disabledBy: [["unbounded"]],
            properties: ["stepped", "wrapped", "excluding_useless_or_dangerous_values"],
        },
        {
            id: "unbounded",
            userEnabled: false,
            type: "2",
            enabledBy: [],
            disabledBy: [["bounded"], ["choice"]],
            properties: [],
        },
        {
            id: "speed_important",
            userEnabled: false,
            type: "2",
            enabledBy: [],
            disabledBy: [["speed_not_important"]],
            properties: ["use_small_muscles"],
        },
        {
            id: "speed_not_important",
            userEnabled: false,
            type: "2",
            enabledBy: [],
            disabledBy: [["speed_important"]],
            properties: ["can_use_big_muscles"],
        },
    ],
    properties: [
        {
            id: "stepped",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "wrapped",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "control_over_each_place_value",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "control_over_degree_of_precision",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "number_is_thing_of_interest",
            userEnabled: false,
            type: "requirement",
            enabledBy: [],
            disabledBy: [],
            properties: ["show_number_in_feedback"],
        },
        {
            id: "show_number_in_feedback",
            userEnabled: false,
            type: "requirement",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "number_not_real_thing_of_interest",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "sketch_of_a number",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "may_evolve_into_needing_precise_value",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "often_random",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "mapped_to_something_unusual",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "form_of_exploration",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "looking_for_surprise",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "breaking_from_self",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "keeping_track_of_something",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "primarily_increasing_not_decreasing",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "limited_selection",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "decreased_range",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "increased_precision",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "minimise_error",
            userEnabled: false,
            type: "requirement",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "adjustment_low_priority",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "adjustment_important",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "prioritise_speed",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "ease_of_comparison_important",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "excluding_useless_or_dangerous_values",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "be_fast!",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "use_small_muscles",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "can_use_big_muscles",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "speed_or_number_of_steps_low_priority",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "avoid_modal_changes",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "fluent_mental_model",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "increment_control",
            userEnabled: false,
            type: "requirement",
            enabledBy: [["counting"]],
            disabledBy: [],
            properties: [],
        },
        {
            id: "decrement_control",
            userEnabled: false,
            type: "property",
            enabledBy: [],
            disabledBy: [],
            properties: [],
        },
        {
            id: "reset_control",
            userEnabled: false,
            type: "requirement",
            enabledBy: [["counting"]],
            disabledBy: [],
            properties: [],
        },
    ],
    links: [],
});
